language: java
sudo: required
jdk:
  - oraclejdk8
services:
  - docker
addons:
  mariadb: '10.1'
before_script:
  - sudo mkdir /etc/smartlambda
  - sudo cp travis/configuration/* /etc/smartlambda
  - mysql -e "CREATE DATABASE IF NOT EXISTS smartlambda;"
  - mysql smartlambda < smartlambda.sql
after_success:
  - gradle :javadoc
  - openssl aes-256-cbc -K $encrypted_c5bc1c58363a_key -iv $encrypted_c5bc1c58363a_iv -in travis/github_deploy_key.enc -out travis/github_deploy_key -d
  - mv travis/github_deploy_key $HOME/.ssh/id_rsa
  - chmod 0600 $HOME/.ssh/id_rsa
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash travis/push_docs.sh