language: java
sudo: required
jdk:
  - oraclejdk8
services:
  - docker
addons:
  mariadb: '10.1'
before_script:
  - sudo mkdir /etc/smartlambda
  - sudo cp travis/configuration/* /etc/smartlambda
  - mysql -e "CREATE DATABASE IF NOT EXISTS smartlambda;"
  - mysql smartlambda < smartlambda.sql
after_success:
  - gradle :javadoc
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash travis/push_docs.sh