version: '2'
services:
  smartlambda:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    restart: always
    privileged: true
  db:
    build: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartlambda
      MYSQL_USER: smartlambda
      MYSQL_PASSWORD:
volumes:
  db_data:
